#!/usr/bin/env ruby

if ARGV.empty?
  puts <<EOS
I'd cheer for you, if only I knew who you were :(
Try again with `./cheers.rb [Name] [MM/DD Birthday]
EOS
else
  name = ARGV[0]
  name.upcase.each_char do |char|
    article = "n" if char == "A"
    puts "Give me a#{article}... #{char}"
  end
  puts "#{name}’s just GRAND!"
  puts ""
  puts "I would wish you a Happy Birthday, if I knew when that was!"
end
